# Generated by Django 4.2.6 on 2023-11-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время старта'),
        ),
    ]
