# Generated by Django 4.2.6 on 2023-11-04 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_mailingsettings_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 11, 12, 10, 47, 74719, tzinfo=datetime.timezone.utc), null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 4, 12, 10, 47, 74564, tzinfo=datetime.timezone.utc), null=True, verbose_name='Время старта'),
        ),
    ]
