# Generated by Django 4.2.6 on 2023-11-05 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 12, 20, 12, 45, 654403, tzinfo=datetime.timezone.utc), null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Время старта'),
        ),
    ]
