# Generated by Django 4.2.6 on 2023-11-04 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_mailingsettings_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 11, 13, 5, 28, 522723, tzinfo=datetime.timezone.utc), null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 4, 13, 5, 28, 522520, tzinfo=datetime.timezone.utc), null=True, verbose_name='Время старта'),
        ),
    ]
